name: Generate snake animation

on:
  schedule: # execute every 12 hours
    - cron: "0 0 * * *" # runs at every 12AM UTC

  workflow_dispatch:

  push:
    branches:
    - main
    
jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - uses: Platane/snk@v3
        name: generate snake.svg 
        with:
          palette: github-dark
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/github-snake.svg
        
      - name: push snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v2.6.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
